/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Simple.Web.Server;

import Models.WebServer;

public class App {
    public static void main(String[] args) {
        WebServer webServer = new WebServer(8081, "D:\\Github\\AboutMe", "D:\\Web\\Logs");
        webServer.start();
    }
}





// Implement GUI for configuration interface and log view

