/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Simple.Web.Server;

import Models.ConfigHandler;
import Models.WebServer;
import com.sun.net.httpserver.HttpExchange;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JScrollBar;
import javax.swing.SwingUtilities;

/**
 *
 * @author lenovo
 */
public class Home extends javax.swing.JFrame {
    WebServer webServer;
    
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPort = new javax.swing.JTextField();
        ApacheButton = new javax.swing.JButton();
        inputWeb = new javax.swing.JTextField();
        inputLog = new javax.swing.JTextField();
        serviceLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FilpWS");
        setResizable(false);

        inputPort.setBackground(new java.awt.Color(225, 225, 225));
        inputPort.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        inputPort.setForeground(new java.awt.Color(102, 102, 102));
        inputPort.setText("8080");
        inputPort.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(120, 120, 120), 1, true));
        inputPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPortActionPerformed(evt);
            }
        });

        ApacheButton.setBackground(new java.awt.Color(66, 142, 255));
        ApacheButton.setFont(new java.awt.Font("Raleway ExtraBold", 0, 12)); // NOI18N
        ApacheButton.setForeground(new java.awt.Color(255, 255, 255));
        ApacheButton.setText("Start");
        ApacheButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 142, 255), 10, true));
        ApacheButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ApacheButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApacheButtonActionPerformed(evt);
            }
        });

        inputWeb.setBackground(new java.awt.Color(225, 225, 225));
        inputWeb.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        inputWeb.setForeground(new java.awt.Color(102, 102, 102));
        inputWeb.setText("D://");
        inputWeb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(120, 120, 120), 1, true));
        inputWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputWebActionPerformed(evt);
            }
        });

        inputLog.setBackground(new java.awt.Color(225, 225, 225));
        inputLog.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        inputLog.setForeground(new java.awt.Color(102, 102, 102));
        inputLog.setText("D://");
        inputLog.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(120, 120, 120), 1, true));
        inputLog.setOpaque(true);
        inputLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLogActionPerformed(evt);
            }
        });

        serviceLabel.setForeground(new java.awt.Color(102, 102, 102));
        serviceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serviceLabel.setText("X");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(225, 225, 225));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setCaretColor(new java.awt.Color(225, 225, 225));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeFrame.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(serviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(462, 462, 462)
                .addComponent(ApacheButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(inputPort, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputLog, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ApacheButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPort, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputLog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ApacheButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApacheButtonActionPerformed

        String webDir = inputWeb.getText();
        String logDir = inputLog.getText();
        int port = Integer.parseInt(inputPort.getText());

        // Save preferences
        ConfigHandler.savePreferences(port, webDir, logDir);

        if (webServer != null && webServer.isRunning()) {
            webServer.stop();
            ApacheButton.setText("Start");
            serviceLabel.setText("X");
        } else {
            webServer = new WebServer(port, webDir, logDir, jTextArea1);
            webServer.start();
            ApacheButton.setText("Stop");
            serviceLabel.setText("✓");
        }
    }//GEN-LAST:event_ApacheButtonActionPerformed

    private void inputPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPortActionPerformed

    private void inputWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputWebActionPerformed

    private void inputLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home home = new Home();
            home.setVisible(true);

            // Load preferences
            int port = ConfigHandler.getPortPreference();
            String webDir = ConfigHandler.getWebDirPreference();
            String logDir = ConfigHandler.getLogDirPreference();

            // Update UI dengan hasil load preferences
            home.inputPort.setText(String.valueOf(port));
            home.inputWeb.setText(webDir);
            home.inputLog.setText(logDir);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApacheButton;
    private javax.swing.JTextField inputLog;
    private javax.swing.JTextField inputPort;
    private javax.swing.JTextField inputWeb;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel serviceLabel;
    // End of variables declaration//GEN-END:variables

}
